export const EU_COUNTRIES = [
  "Austria",
  "Belgium",
  "Bulgaria",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Greece",
  "Hungary",
  "Ireland",
  "Italy",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malta",
  "Netherlands",
  "Poland",
  "Portugal",
  "Romania",
  "Slovakia",
  "Slovenia",
  "Spain",
  "Sweden",
] as const;

export type Country = (typeof EU_COUNTRIES)[number];

export const MEPS_BY_COUNTRY: Record<Country, string[]> = {
  Austria: [
    "Harald Vilimsky",
    "Petra Steger",
    "Georg Mayer",
    "Roman Haider",
    "Gerald Hauser",
    "Elisabeth Dieringer",
    "Reinhold Lopatka",
    "Angelika Winzig",
    "Alexander Bernhuber",
    "Sophia Kircher",
    "Lukas Mandl",
    "Andreas Schieder",
    "Evelyn Regner",
    "Günther Sidl",
    "Elisabeth Grossmann",
    "Hannes Heide",
    "Lena Schilling",
    "Thomas Waitz",
    "Helmut Brandstätter",
    "Anna Stürgkh",
  ],
  Belgium: [
    "Wouter Beke",
    "Pascal Arimont",
    "Barbara Bonte",
    "Marc Botenga",
    "Saskia Bricmont",
    "Benoit Cassart",
    "Estelle Ceulemans",
    "Olivier Chastel",
    "Elio Di Rupo",
    "Assita Kanko",
    "Rudi Kennes",
    "Sara Matthieu",
    "Liesbet Sommen",
    "Bruno Tobback",
    "Tom Vandendriessche",
    "Kris Van Dijck",
    "Johan Van Overtveldt",
    "Hilde Vautmans",
    "Kathleen Van Brempt",
    "Yvan Verougstraete",
    "Sophie Wilmès",
  ],
  Bulgaria: [
    "Radan Kanev",
    "Eva Maydell",
    "Andrey Novakov",
    "Emil Radev",
    "Andrey Kovatchev",
    "Tsvetelina Penkova",
    "Kristian Vigenin",
    "Ilhan Kyuchyuk",
    "Nikola Minchev",
    "Hristo Petrov",
    "Taner Kabilov",
    "Elena Yoncheva",
    "Ilia Lazarov",
    "Rada Laykova",
    "Stanislav Stoyanov",
    "Petar Volgin",
    "Ivaylo Valchev",
  ],
  Croatia: [
    "Nikolina Brnjac",
    "Sunčana Glavak",
    "Karlo Ressler",
    "Davor Ivo Stier",
    "Tomislav Sokol",
    "Željana Zovko",
    "Biljana Borzan",
    "Romana Jerković",
    "Tonino Picula",
    "Marko Vešligaj",
    "Gordan Bosanac",
    "Stephen Nikola Bartulica",
  ],
  Cyprus: [
    "Loucas Fourlas",
    "Michalis Hadjipantela",
    "David Casa",
    "Costas Mavrides",
    "Giorgos Georgiou",
    "Geadis Geadi",
    "Fidias Panayiotou",
  ],
  "Czech Republic": [
    "Jan Farský",
    "Ondřej Kolář",
    "Luděk Niedermayer",
    "Danuše Nerudová",
    "Tomáš Zdechovský",
    "Markéta Gregorová",
    "Ondřej Krutílek",
    "Veronika Vrecionová",
    "Alexandr Vondra",
    "Jaroslav Bžoch",
    "Klara Dostalova",
    "Ondřej Knotek",
    "Jaroslav Knot",
    "Tomáš Kubín",
    "Jana Nagyová",
    "Jaroslava Pokorná Jermanová",
    "Filip Turek",
    "Nikola Bartůšek",
    "Ondřej Dostál",
    "Kateřina Konečná",
    "Ivan David",
  ],
  Denmark: [
    "Henrik Dahl",
    "Asger Christensen",
    "Stine Bosse",
    "Sigrid Friis",
    "Morten Løkkegaard",
    "Niels Flemming Hansen",
    "Christel Schaldemose",
    "Marianne Vind",
    "Niels Fuglsang",
    "Rasmus Nordqvist",
    "Kira Marie Peter-Hansen",
    "Villy Søvndal",
    "Per Clausen",
    "Kristoffer Storm",
    "Anders Vistisen",
  ],
  Estonia: [
    "Marina Kaljurand",
    "Sven Mikser",
    "Urmas Paet",
    "Jana Toom",
    "Jüri Ratas",
    "Riho Terras",
    "Jaak Madison",
  ],
  Finland: [
    "Mika Aaltola",
    "Li Andersson",
    "Anna-Maja Henriksson",
    "Elsi Katainen",
    "Katri Kulmuni",
    "Maria Guzenina",
    "Eero Heinäluoma",
    "Sirpa Pietikäinen",
    "Aura Salla",
    "Pekka Toveri",
    "Ville Niinistö",
    "Maria Ohisalo",
    "Jussi Saramo",
    "Merja Kyllönen",
    "Sebastian Tynkkynen",
  ],
  France: [
    "François-Xavier Bellamy",
    "Gilles Boyer",
    "Pascal Canfin",
    "Damien Carême",
    "Laurent Castillo",
    "Leila Chaibi",
    "Christophe Clergeau",
    "David Cormand",
    "Marie Dauchy",
    "Mathilde Androuët",
    "Valérie Devaux",
    "Mélanie Disdier",
    "Claire Fita",
    "Emma Fourreau",
    "Anne-Sophie Frigout",
    "Angéline Furet",
    "Jean-Paul Garraud",
    "Jean-Marc Germain",
    "Sandro Gozi",
    "Bernard Guetta",
    "Christophe Grudler",
    "Valérie Hayer",
    "Céline Imart",
    "France Jamet",
    "Virginie Joron",
    "Pierre Jouvet",
    "François Kalfon",
    "Fabienne Keller",
    "Sarah Knafo",
    "Aurore Lalucq",
    "Isabelle Le Callennec",
    "Fabrice Leggeri",
    "Julien Leonardelli",
    "Nathalie Loiseau",
    "Thierry Mariani",
    "Marion Maréchal",
    "Nora Mebarek",
    "Nadine Morano",
    "Aleksandar Nikolic",
    "Philippe Olivier",
    "Younous Omarjee",
    "Guillaume Peltier",
    "Gilles Pennelle",
    "Pascale Piera",
    "Pierre Pimpie",
    "Emma Rafowicz",
    "Julie Rechagneux",
    "Chloé Ridel",
    "André Rougé",
    "Arash Saeidi",
    "Julien Sanchez",
    "Eric Sargiacomo",
    "Mounir Satouri",
    "Majdouline Sbai",
    "Anthony Smith",
    "Malika Sorel",
    "Marie Toussaint",
    "Laurence Trochu",
    "Alexandre Varaut",
    "Marie-Pierre Vedrenne",
    "Séverine Werbrouck",
    "Stéphanie Yon-Courtin",
    "Jordan Bardella",
    "Nicolas Bay",
    "Christophe Bay",
    "Marie-Luce Brasier-Clain",
    "Mélissa Camara",
    "Valérie Deloge",
    "Laurence Farreng",
    "Grégory Allione",
    "Christophe Gomart",
    "Catherine Griset",
    "Rima Hassan",
    "Céline Imart",
    "Pierre Jouvet",
    "Murielle Laurent",
    "Marina Mesure",
    "Raphaël Glucksmann",
    "Thomas Pellerin-Carlin",
    "Pierre-Romain Thionnet",
    "Rody Tolassy",
    "Matthieu Valet",
  ],
  Germany: [
    "Christine Schneider",
    "Birgit Sippel",
    "René Repasi",
    "Maria Noichl",
    "Jan-Christoph Oetjen",
    "Terry Reintke",
    "Katarina Barley",
    "Marie-Agnes Strack-Zimmermann",
    "Axel Voss",
    "Norbert Lins",
    "Christine Anderson",
    "Rasmus Andresen",
    "Hildegard Bentele",
    "Stefan Berger",
    "Sibylle Berg",
    "Gabriele Bischoff",
    "Michael Bloss",
    "Damian Boeselager",
    "Markus Buchheit",
    "Udo Bullmann",
    "Delara Burkhardt",
    "Petr Bystron",
    "Daniel Caspary",
    "Anna Cavazzini",
    "Tobias Cremer",
    "Fabio De Masi",
    "Özlem Demirel",
    "Christian Doleschal",
    "Lena Düpont",
    "Matthias Ecke",
    "Christian Ehler",
    "Bas Eickhout",
    "Engin Eroglu",
    "Sebastian Everding",
    "Markus Ferber",
    "Ruth Firmenich",
    "Daniel Freund",
    "Tomasz Froelich",
    "Michael Gahler",
    "Jens Geier",
    "Thomas Geisel",
    "Niels Geuking",
    "Jens Gieseke",
    "Andreas Glück",
    "Martin Günther",
    "Svenja Hahn",
    "Martin Häusling",
    "Niclas Herbst",
    "Monika Hohlmeier",
    "Marc Jongen",
    "Alexander Jungbluth",
    "Mary Khan",
    "Stefan Köhler",
    "Moritz Körner",
    "Sergey Lagodinsky",
    "Bernd Lange",
    "Katrin Langensiepen",
    "Peter Liese",
    "David McAllister",
    "Alexandra Mehnert",
    "Verena Mertens",
    "Hans Neuhoff",
    "Hannah Neumann",
    "Angelika Niebler",
    "Jutta Paulus",
    "Friedrich Pürner",
    "Dennis Radtke",
    "Martin Schirdewan",
    "Volker Schnurrbusch",
    "Andreas Schwab",
    "Ralf Seekatz",
    "Alexander Sell",
    "Sven Simon",
    "Christine Singer",
    "Joachim Streit",
    "Kai Tegethoff",
    "Sabine Verheyen",
    "Michael Von Der Schulenburg",
    "Marion Walsmann",
    "Jan-Peter Warnke",
    "Manfred Weber",
    "Andrea Wechsler",
    "Tiemo Wölken",
    "Vivien Costanzo",
    "Alexandra Geese",
    "Nela Riehl",
    "Manuela Ripa",
    "Lukas Sieper",
    "Martin Sonneborn",
    "Arno Bausemer",
    "Irmhild Boßdorf",
    "Siegbert Frank Droese",
  ],
  Greece: [
    "Georgios Aftias",
    "Galato Alexandraki",
    "Nikolaos Anadiotis",
    "Sakis Arnaoutoglou",
    "Konstantinos Arvanitis",
    "Fredis Beleris",
    "Emmanouil Fragkos",
    "Nikolas Farantouris",
    "Emmanouil Kefalogiannis",
    "Elena Kountoura",
    "Afroditi Latinopoulou",
    "Yannis Maniatis",
    "Vangelis Meimarakis",
    "Eleonora Meleti",
    "Lefteris Nikolaou-Alavanos",
    "Nikos Papandreou",
    "Nikos Pappas",
    "Kostas Papadakis",
    "Dimitris Tsiodras",
    "Elissavet Vozemberg-Vrionidi",
    "Maria Zacharia",
  ],
  Hungary: [
    "Dóra Dávid",
    "Tamás Deutsch",
    "Klára Dobrev",
    "Csaba Dömötör",
    "Viktória Ferenc",
    "Kinga Gál",
    "Gabriella Gerzsenyi",
    "Enikő Győri",
    "András Gyürk",
    "György Hölvényi",
    "Kinga Kollár",
    "András Tivadar Kulja",
    "Eszter Lakos",
    "András László",
    "Péter Magyar",
    "Csaba Molnár",
    "Ernő Schaller-Baross",
    "Pál Szekeres",
    "Zoltán Tarr",
    "Annamária Vicsek",
    "Zsuzsanna Borvendég",
  ],
  Ireland: [
    "Barry Andrews",
    "Nina Carberry",
    "Barry Cowen",
    "Regina Doherty",
    "Kathleen Funchion",
    "Seán Kelly",
    "Billy Kelleher",
    "Michael McNamara",
    "Ciaran Mullooly",
    "Cynthia Ní Mhurchú",
    "Aodhán Ó Ríordáin",
    "Maria Walsh",
    "Lynn Boylan",
    "Luke Ming Flanagan",
  ],
  Italy: [
    "Lucia Annunziata",
    "Giuseppe Antoci",
    "Sergio Berlato",
    "Brando Benifei",
    "Paolo Borchia",
    "Stefano Bonaccini",
    "Stefano Cavedagna",
    "Susanna Ceccardi",
    "Caterina Chinnici",
    "Carlo Ciccioli",
    "Alessandro Ciriani",
    "Anna Maria Cisint",
    "Annalisa Corrado",
    "Giovanni Crosetto",
    "Antonio Decaro",
    "Danilo Della Valle",
    "Salvatore De Meo",
    "Elena Donazzan",
    "Herbert Dorfmann",
    "Carlo Fidanza",
    "Pietro Fiocchi",
    "Mario Furore",
    "Alberico Gambino",
    "Chiara Gemma",
    "Giorgio Gori",
    "Cristina Guarda",
    "Elisabetta Gualmini",
    "Camilla Laureti",
    "Giuseppe Lupo",
    "Lara Magoni",
    "Mario Mantovani",
    "Pierfrancesco Maran",
    "Ignazio Roberto Marino",
    "Fulvio Martusciello",
    "Giuseppe Milazzo",
    "Carolina Morace",
    "Letizia Moratti",
    "Alessandra Moretti",
    "Dario Nardella",
    "Denis Nesci",
    "Leoluca Orlando",
    "Valentina Palmisano",
    "Aldo Patriciello",
    "Gaetano Pedulla'",
    "Michele Picaro",
    "Pina Picierno",
    "Daniele Polato",
    "Giusi Princi",
    "Nicola Procaccini",
    "Ruggero Razza",
    "Matteo Ricci",
    "Sandro Ruotolo",
    "Ilaria Salis",
    "Massimiliano Salini",
    "Silvia Sardone",
    "Antonella Sberna",
    "Benedetta Scuderi",
    "Marco Squarta",
    "Raffaele Stancanelli",
    "Cecilia Strada",
    "Dario Tamburrano",
    "Marco Tarquinio",
    "Irene Tinagli",
    "Raffaele Topo",
    "Francesco Torselli",
    "Flavio Tosi",
    "Isabella Tovaglieri",
    "Pasquale Tridico",
    "Roberto Vannacci",
    "Francesco Ventola",
    "Mariateresa Vivaldini",
    "Alessandro Zan",
    "Nicola Zingaretti",
    "Marco Falcone",
    "Paolo Inselvini",
    "Mimmo Lucano",
  ],
  Latvia: [
    "Sandra Kalniete",
    "Inese Vaidere",
    "Ivars Ijabs",
    "Rihards Kols",
    "Vilis Krištopans",
    "Reinis Pozņaks",
    "Nils Ušakovs",
    "Mārtiņš Staķis",
  ],
  Lithuania: [
    "Vytenis Povilas Andriukaitis",
    "Petras Auštrevičius",
    "Vilija Blinkevičiūtė",
    "Rasa Juknevičienė",
    "Liudas Mažylis",
    "Paulius Saudargas",
    "Virginijus Sinkevičius",
    "Waldemar Tomaszewski",
    "Aurelijus Veryga",
    "Dainius Žalimas",
    "Petras Gražulis",
  ],
  Luxembourg: [
    "Marc Angel",
    "Charles Goerens",
    "Martine Kemp",
    "Tilly Metz",
    "Isabel Wiseler-Lima",
    "Fernand Kartheiser",
  ],
  Malta: [
    "Peter Agius",
    "Alex Agius Saliba",
    "Daniel Attard",
    "Thomas Bajada",
    "David Casa",
    "Roberta Metsola",
  ],
  Netherlands: [
    "Malik Azmani",
    "Jeannette Baljeu",
    "Tom Berendsen",
    "Rachel Blom",
    "Mohammed Chahim",
    "Ton Diepeveen",
    "Bas Eickhout",
    "Marieke Ehlers",
    "Raquel García Hermida-Van Der Walle",
    "Gerben-Jan Gerbrandy",
    "Dirk Gotink",
    "Bart Groothuis",
    "Anja Hazekamp",
    "Sebastian Kruis",
    "Jeroen Lenaers",
    "Marit Maij",
    "Thijs Reuten",
    "Bert-Jan Ruissen",
    "Sander Smit",
    "Tineke Strik",
    "Anna Strolenberg",
    "Sebastiaan Stöteler",
    "Ingeborg Ter Laak",
    "Anouk Van Brug",
    "Brigitte Van Den Berg",
    "Reinier Van Lanschot",
    "Jessika Van Leeuwen",
    "Kim Van Sparrentak",
    "Catarina Vieira",
    "Lara Wolters",
    "Auke Zijlstra",
  ],
  Poland: [
    "Janusz Lewandowski",
    "Magdalena Adamowicz",
    "Piotr Müller",
    "Krzysztof Brejza",
    "Kosma Złotowski",
    "Jacek Protas",
    "Maciej Wąsik",
    "Michał Kobosko",
    "Ewa Zajączkowska-Hernik",
    "Kamila Gasiuk-Pihowicz",
    "Michał Szczerba",
    "Hanna Gronkiewicz-Waltz",
    "Robert Biedroń",
    "Małgorzata Gosiewska",
    "Tobiasz Bocheński",
    "Andrzej Halicki",
    "Adam Bielan",
    "Jacek Ozdoba",
    "Dariusz Joński",
    "Waldemar Buda",
    "Krzysztof Hetman",
    "Anna Bryłka",
    "Ewa Kopacz",
    "Michał Wawrykiewicz",
    "Joanna Scheuring-Wielgus",
    "Marlena Maląg",
    "Marta Wcisło",
    "Mariusz Kamiński",
    "Tomasz Buczek",
    "Elżbieta Łukacijewska",
    "Daniel Obajtek",
    "Bogdan Rzońca",
    "Adam Jarubas",
    "Grzegorz Braun",
    "Bartłomiej Sienkiewicz",
    "Jagna Marczułajtis-Walczak",
    "Beata Szydło",
    "Arkadiusz Mularczyk",
    "Dominik Tarczyński",
    "Marcin Sypniewski",
    "Borys Budka",
    "Mirosława Nykiel",
    "Łukasz Kohut",
    "Jadwiga Wiśniewska",
    "Patryk Jaki",
    "Stanisław Tyszka",
    "Bogdan Zdrojewski",
    "Andrzej Buła",
    "Krzysztof Śmiszek",
    "Anna Zalewska",
    "Michał Dworczyk",
    "Bartosz Arłukowicz",
    "Joachim Brudziński",
  ],
  Portugal: [
    "Francisco Assis",
    "Sebastião Bugalho",
    "João Cotrim De Figueiredo",
    "Paulo Cunha",
    "Isilda Gomes",
    "Bruno Gonçalves",
    "Sérgio Gonçalves",
    "Sérgio Humberto",
    "Catarina Martins",
    "Ana Catarina Mendes",
    "Tiago Moreira De Sá",
    "Paulo Do Nascimento Cabral",
    "João Oliveira",
    "Ana Miguel Pedro",
    "Lídia Pereira",
    "André Rodrigues",
    "Hélder Sousa Silva",
    "António Tânger Corrêa",
    "Carla Tavares",
    "Marta Temido",
    "Ana Vasconcelos",
  ],
  Romania: [
    "Ioan-Rareş Bogdan",
    "Dragoş Benea",
    "Dan Barna",
    "Gheorghe Cârciu",
    "Andi Cristea",
    "Vasile Dîncu",
    "Gheorghe Falcă",
    "Gabriela Firea",
    "Maria Grapini",
    "Mircea-Gheorghe Hava",
    "Diana Iovanovici Şoşoacă",
    "Luis-Vicențiu Lazarus",
    "Claudiu Manda",
    "Dan-Ştefan Motreanu",
    "Siegfried Mureşan",
    "Ştefan Muşoiu",
    "Victor Negrescu",
    "Dan Nica",
    "Gheorghe Piperea",
    "Virgil-Daniel Popescu",
    "Nicolae Ştefănuță",
    "Şerban Dimitrie Sturdza",
    "Claudiu-Richard Târziu",
    "Georgiana Teodorescu",
    "Cristian Terheş",
    "Eugen Tomac",
    "Mihai Tudose",
    "Adina Vălean",
    "Vlad Vasile-Voiculescu",
    "Loránt Vincze",
    "Iuliu Winkler",
    "Adrian-George Axinia",
    "Daniel Buda",
  ],
  Slovakia: [
    "Monika Beňová",
    "Ľuboš Blaha",
    "Veronika Cifrová Ostrihoňová",
    "Martin Hojsík",
    "Erik Kaliňák",
    "Ľubica Karvašová",
    "Judita Laššáková",
    "Miriam Lexmann",
    "Milan Mazurek",
    "Ľudovít Ódor",
    "Branislav Ondruš",
    "Katarína Roth Neveďalová",
    "Milan Uhrík",
    "Michal Wiezik",
    "Lucia Yar",
  ],
  Slovenia: [
    "Branko Grims",
    "Irena Joveva",
    "Matjaž Nemec",
    "Vladimir Prebilič",
    "Marjan Šarec",
    "Zala Tomašič",
    "Romana Tomc",
    "Matej Tonin",
    "Milan Zver",
  ],
  Spain: [
    "Maravillas Abadía Jover",
    "Pablo Arias Echeverría",
    "Jaume Asens Llodrà",
    "Laura Ballarín Cereza",
    "Pernando Barrena Arza",
    "Isabel Benjumea Benjumea",
    "Mireia Borrás Pabón",
    "Jorge Buxadé Villalba",
    "José Cepeda",
    "Carmen Crespo Díaz",
    "Pilar Del Castillo Vera",
    "Raúl De La Hoz Quintano",
    "Rosa Estaràs Ferragut",
    "Alma Ezcurra Almansa",
    "Jonás Fernández",
    "Estrella Galán",
    "Lina Gálvez",
    "Iratxe García Pérez",
    "Borja Giménez Larraz",
    "Juan Carlos Girauta Vidal",
    "Sandra Gómez López",
    "Nicolás González Casares",
    "Esteban González Pons",
    "Esther Herranz García",
    "Alicia Homs Ginel",
    "Hana Jalloul Muro",
    "Antonio López-Istúriz White",
    "Juan Fernando López Aguilar",
    "Javi López",
    "César Luena",
    "Cristina Maestre",
    "Jorge Martín Frías",
    "Vicent Marzà Ibáñez",
    "Gabriel Mato",
    "Idoia Mendia",
    "Francisco José Millán Mon",
    "Ana Miranda Paz",
    "Irene Montero",
    "Dolors Montserrat",
    "Javier Moreno Sánchez",
    "Fernando Navarrete Rojas",
    "Elena Nevado Del Campo",
    "Leire Pajín",
    "Nicolás Pascual De La Parte",
    "Alvise Pérez",
    "Margarita De La Pisa Carrión",
    "Diana Riba I Giner",
    "Marcos Ros Sempere",
    "Nacho Sánchez Amor",
    "Elena Sancho Murillo",
    "Rosa Serrano Sierra",
    "Isabel Serra Sánchez",
    "Diego Solier",
    "Susana Solís Pérez",
    "Hermann Tertsch",
    "Adrián Vázquez Lázara",
    "Javier Zarzalejos",
    "Juan Ignacio Zoido Álvarez",
    "Nora Junco García",
  ],
  Sweden: [
    "Abir Al-Sahlani",
    "Li Andersson",
    "Johan Danielsson",
    "Adnan Dibrani",
    "Dick Erixon",
    "Sofie Eriksson",
    "Heléne Fritzon",
    "Hanna Gedin",
    "Pär Holmgren",
    "Evin Incir",
    "Karin Karlsbro",
    "Arba Kokalari",
    "Alice Kuhnke",
    "Isabella Lövin",
    "Jessica Polfjärd",
    "Jonas Sjöstedt",
    "Alice Teodorescu Måwe",
    "Beatrice Timgren",
    "Tomas Tobé",
    "Jörgen Warborn",
    "Charlie Weimers",
    "Emma Wiesner",
  ],
};
